In [1]:
import torch

In [23]:
x = torch.tensor([1, 2, 3], dtype=torch.float64, requires_grad=True)
w = torch.tensor([2, 3, 4], dtype=torch.float64, requires_grad=True)


In [8]:
w.unsqueeze(-1)

tensor([[2],
        [3],
        [4]])

In [24]:
c = x*(w.unsqueeze(-1))

In [16]:
c

tensor([[ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12]])

In [30]:
d = c.sum()

In [31]:
d.backward()

In [32]:
w.grad

tensor([6., 6., 6.], dtype=torch.float64)

In [44]:
x.grad

tensor([9., 9., 9.], dtype=torch.float64)

In [51]:
c@w

tensor([40., 60., 80.], dtype=torch.float64, grad_fn=<MvBackward>)