In [2]:
import numpy as np

In [2]:
# basic array creation
np.array([1, 2, 3, 4, 5,])

array([1, 2, 3, 4, 5])

Массивы в np гомогенны, так что при создании он попытается привести их к общему типу

In [3]:
# в данном случае - к числам с плавающей точкой
np.array([3,14, 2.78, 4, 5, 19])

array([ 3.  , 14.  ,  2.78,  4.  ,  5.  , 19.  ])

In [4]:
# или можно задавать тип непосредственно при инициализации
np.array([1, 2, 3, 4, 5], dtype="float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
# вложенные списки преобразуются в многомерный массив
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Большие массивы эффективнее создавать с нуля, используя специальные методы

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# заполняем массив 5х6 указанным значением
np.full((5, 6), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# метод, аналогичный стандартному range
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Создаем массив из пяти значений,
# равномерно располагающихся между 0 и 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# равномерно распределенные случайные значения
np.random.random((3,3))

array([[0.06975769, 0.96036154, 0.92005154],
       [0.83272675, 0.63136589, 0.51153471],
       [0.82218084, 0.55912751, 0.71425065]])

In [15]:
# нормально распределенные с медианой 0 и std 1
np.random.normal(0, 1, (3,3))

array([[-1.90369251, -0.77543624,  1.93261708],
       [ 0.47364952, -0.51772666,  1.18583365],
       [-2.82128351, -0.93926153, -1.83014131]])

In [16]:
# Создаем массив размером 3 x 3 случайных целых числа
# в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 8, 0],
       [0, 5, 2],
       [1, 1, 8]])

In [17]:
# Создаем единичную матрицу размером 3 x 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

### Атрибуты массивов

In [20]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype:  int64


### Индексация

In [4]:
x1 = np.array([1,2,2,1])
x1[0] == x1[-1] # ничего неожиданного

True

In [8]:
x3 = np.random.randint(10, size=(3,4,5))
x3


array([[[2, 2, 7, 7, 1],
        [2, 1, 9, 6, 5],
        [3, 0, 9, 9, 6],
        [3, 6, 6, 8, 9]],

       [[2, 0, 3, 1, 6],
        [6, 1, 3, 5, 0],
        [3, 7, 7, 8, 0],
        [1, 5, 4, 6, 8]],

       [[8, 7, 5, 8, 5],
        [8, 6, 2, 6, 7],
        [3, 0, 3, 2, 4],
        [1, 9, 0, 0, 8]]])

In [25]:
x3[2,2,2]

3

In [26]:
x3[2,3,3] = 666
x3

array([[[  2,   2,   7,   7,   1],
        [  2,   1,   9,   6,   5],
        [  3,   0,   9,   9,   6],
        [  3,   6,   6,   8,   9]],

       [[  2,   0,   3,   1,   6],
        [  6,   1,   3,   5,   0],
        [  3,   7,   7,   8,   0],
        [  1,   5,   4,   6,   8]],

       [[  8,   7,   5,   8,   5],
        [  8,   6,   2,   6,   7],
        [  3,   0,   3,   2,   4],
        [  1,   9,   0, 666,   8]]])

Срезы одномерных массивов работают аналогично стандартной библиотеке, а вот к многомерным надо привыкать

In [28]:
x3[:1, :2, :3] # первая матрица, две строки, три столбца

array([[[2, 2, 7],
        [2, 1, 9]]])

### Доступ к строкам и столбцам

In [30]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[4, 3, 4, 6],
       [0, 0, 6, 2],
       [7, 5, 3, 3]])

In [32]:
x2[1,:] # строка

array([0, 0, 6, 2])

In [33]:
x2[:, 2] # стобец

array([4, 6, 3])

Срезы возвращают не копии данных, а т.н. views, так что изменения объекта, содержащего срез, изменяет исходный список. Копии создаются через метод .copy()

### Изменение размерности

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x = np.array([1,2,3]) # одномерный массив
x

array([1, 2, 3])

In [43]:
x.reshape((1,3)) # двумерная матрица-строка

array([[1, 2, 3]])

In [44]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

### Слияние и разделение массивов

In [45]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [46]:
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
grid = np.array([[9,8,7], [6,5,4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [48]:
np.vstack([x, grid]) # объединить по вертикали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [50]:
y = np.array([[99], [99]])
np.hstack([grid, y]) # по горизонтали

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Векторизованные операции

In [51]:
values = np.random.randint(1, 10, size=5)
1 / values 

array([0.5       , 0.125     , 0.14285714, 0.16666667, 0.2       ])

In [52]:
2 ** values

array([  4, 256, 128,  64,  32])

In [53]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [54]:
x = np.arange(4)
print("x=", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x= [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [55]:
x = [1, 2, 3]
print("x=", x)
print("e^x=", np.exp(x))
print("2^x=", np.exp2(x))
print("3^x=", np.power(3, x))

x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]
